// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd2Z8O64tLYWT_DlBuKdZ6FUKC8Kil_eg',
    appId: '1:884237424029:web:966468ba83960e1629cb74',
    messagingSenderId: '884237424029',
    projectId: 'attendance-app-775f6',
    authDomain: 'attendance-app-775f6.firebaseapp.com',
    storageBucket: 'attendance-app-775f6.appspot.com',
    measurementId: 'G-8L0L8JNTCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVGoAEy4o_S8MHuiVHnsoJLTPZdod0_8',
    appId: '1:884237424029:android:6f3f3e0e39c3b44829cb74',
    messagingSenderId: '884237424029',
    projectId: 'attendance-app-775f6',
    storageBucket: 'attendance-app-775f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-FNQ16UIKGu3Iq-U9Rc9SwzLuRxWBaE4',
    appId: '1:884237424029:ios:68a6a49f767e88b029cb74',
    messagingSenderId: '884237424029',
    projectId: 'attendance-app-775f6',
    storageBucket: 'attendance-app-775f6.appspot.com',
    iosClientId: '884237424029-2jer74kgeif1jnglhthi6tlh7jp05lsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sjcetLeave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-FNQ16UIKGu3Iq-U9Rc9SwzLuRxWBaE4',
    appId: '1:884237424029:ios:68a6a49f767e88b029cb74',
    messagingSenderId: '884237424029',
    projectId: 'attendance-app-775f6',
    storageBucket: 'attendance-app-775f6.appspot.com',
    iosClientId: '884237424029-2jer74kgeif1jnglhthi6tlh7jp05lsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sjcetLeave',
  );
}
